CREATE TABLE IF NOT EXISTS users(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nick VARCHAR(16) UNIQUE NOT NULL,
    password_hash VARCHAR(256) NOT NULL
);
INSERT INTO users(id, nick, password_hash) VALUES (0, 'deleted user', '');

CREATE TABLE IF NOT EXISTS chats(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(16) UNIQUE NOT NULL
);

INSERT INTO chats(name) VALUES ("#global");

CREATE TABLE IF NOT EXISTS messages(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    author_id TEXT NOT NULL REFERENCES users(id),
    chat_id TEXT NOT NULL REFERENCES chats(id),
    created_at TIMESTAMP DEFAULT NOW NOT NULL,
    text_ TEXT NOT NULL
);